import type { OpenAdminPlugin } from "@openadminjs/plugin-sdk";

/**
 * Copy this file into your app under `apps/api/src/plugins/custom/` and add
 * its package/bundled entry into `apps/api/plugins.manifest.json`.
 */
export const welcomeAiPlugin: OpenAdminPlugin = {
  id: "com.example.welcome-ai",
  version: "0.1.0",
  register({ registerSurface }) {
    registerSurface({
      seo: {
        metadata({ resourceName, record }) {
          if (resourceName !== "posts") return {};
          return {
            title: record.title ?? "Untitled post",
            description: "Generated by custom plugin example"
          };
        }
      },
      adminUi: [
        {
          kind: "menu",
          id: "ai-helper",
          title: "AI helper",
          route: "/plugins"
        }
      ]
    });
  }
};
