/**
 * Public brand asset paths for the admin app.
 * Assets are generated by `pnpm brand:assets` from `openadminjs-logo-new.png`.
 * To regenerate, run `pnpm brand:assets` from the repo root.
 */
export const BRAND = {
  /** SVG favicon wrapper generated from logo mark */
  favicon: "/brand/favicon.svg",
  faviconPng: "/brand/openadminjs-icon-new.png",
  appleTouch: "/brand/apple-touch-icon.png",
  ogImage: "/brand/og-image.png",
  logoNew: "/brand/openadminjs-logo-new.png",
  logoMonochromePng: "/brand/openadminjs-logo-monochrome.png"
} as const;
